"""
Auto-PR creation after successful pi agent runs.

When pi commits code and tests pass, create a PR so humans can review.
"""

import subprocess
from pathlib import Path
from typing import Optional

from .issue_queue import QueueItem


def create_pr_for_item(
    repo_path: Path,
    item: QueueItem,
    branch_name: Optional[str] = None,
) -> Optional[int]:
    """Create a PR for the current branch, linked to the issue.

    Returns PR number on success, None on failure.
    """
    repo_path = Path(repo_path).resolve()

    # Get current branch
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=repo_path, capture_output=True, text=True, timeout=10,
        )
        current_branch = result.stdout.strip()
    except Exception:
        return None

    if current_branch in ("main", "master"):
        # pi committed directly to main -- no PR needed, already landed
        return None

    if not branch_name:
        branch_name = current_branch

    # Build PR title and body
    title = f"[AIPM] {item.title}"
    body = f"Auto-generated by AIPM for #{item.issue_number}.\n\nCloses #{item.issue_number}"

    # Add task progress
    completed, total = item.task_checklist
    if total > 0:
        body += f"\n\n**Progress:** {completed}/{total} tasks completed"

    try:
        result = subprocess.run(
            [
                "gh", "pr", "create",
                "--title", title,
                "--body", body,
                "--label", "autospec",
                "--base", "main",
            ],
            cwd=repo_path, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            # Parse PR number from URL
            url = result.stdout.strip()
            pr_num = int(url.rstrip("/").split("/")[-1])
            return pr_num
        else:
            # PR might already exist for this branch
            if "already exists" in result.stderr.lower():
                return _get_existing_pr(repo_path, branch_name)
    except (subprocess.TimeoutExpired, FileNotFoundError, ValueError):
        pass
    return None


def _get_existing_pr(repo_path: Path, branch: str) -> Optional[int]:
    """Find an existing PR for this branch."""
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--head", branch, "--json", "number", "--limit", "1"],
            cwd=repo_path, capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0:
            import json
            prs = json.loads(result.stdout)
            if prs:
                return prs[0]["number"]
    except Exception:
        pass
    return None


def get_or_create_branch(repo_path: Path, item: QueueItem) -> str:
    """Ensure we're on a feature branch for this issue.

    If on main/master, create and checkout a branch.
    Returns the branch name.
    """
    repo_path = Path(repo_path).resolve()

    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=repo_path, capture_output=True, text=True, timeout=10,
    )
    current = result.stdout.strip()

    if current not in ("main", "master"):
        return current

    # Create a branch named aipm/<issue-number>-<slug>
    slug = item.title.lower()
    slug = "".join(c if c.isalnum() else "-" for c in slug).strip("-")[:40]
    branch = f"aipm/{item.issue_number}-{slug}"

    subprocess.run(
        ["git", "checkout", "-b", branch],
        cwd=repo_path, capture_output=True, text=True, timeout=10,
    )
    return branch
