"""
Follow-up issue creation.

When AIPM successfully completes an issue, this module:
  1. Scans the completed issue body for unchecked tasks
  2. Reads the diff to understand what was actually implemented
  3. Identifies natural follow-up work (tests, docs, integration)
  4. Creates well-structured GitHub issues for the next work items

This makes AIPM self-feeding: completing work generates more work.
"""

import re
from typing import List, Optional
from .issue_queue import GitHubIssueQueue, QueueItem


def create_followup_issues(
    queue: GitHubIssueQueue,
    item: QueueItem,
    diff_summary: str = "",
    tests_before: int = 0,
    tests_after: int = 0,
    max_issues: int = 2,
) -> List[int]:
    """Analyze a completed issue and create follow-up issues.

    Returns list of created issue numbers.
    """
    created = []
    body = item.body
    existing_titles = [i.title.lower() for i in queue.list_open()]

    # ── 1. Extract unchecked tasks from the original issue ──
    unchecked = _extract_unchecked_tasks(body)
    if unchecked and len(created) < max_issues:
        task_list = "\n".join(f"- [ ] {t}" for t in unchecked)
        followup_title = f"[Follow-up] Remaining tasks from #{item.issue_number}"

        # Skip if a similar follow-up already exists
        if not _title_matches(followup_title.lower(), existing_titles):
            followup_body = (
                f"## Remaining Tasks from #{item.issue_number}\n\n"
                f"**Original issue:** #{item.issue_number} -- {item.title}\n\n"
                f"Core implementation was completed, but these tasks remain:\n\n"
                f"{task_list}\n\n"
                f"---\n"
                f"_Auto-generated by AIPM follow-up scanner after completing #{item.issue_number}_"
            )

            # Inherit priority from parent
            priority = "medium"
            for label in item.labels:
                if label.startswith("priority:"):
                    priority = label.split(":")[1]
                    break

            issue_num = queue.create_issue(
                title=followup_title,
                body=followup_body,
                labels=["autospec", "spec-defined", f"priority:{priority}"],
            )
            if issue_num:
                created.append(issue_num)
                existing_titles.append(followup_title.lower())

    # ── 2. Detect missing test coverage ──
    # Only trigger if tests DECREASED (regression) -- not if they're stable.
    # Stable tests with code changes is normal (features, configs, refactors).
    # The old logic triggered on tests_after <= tests_before which was too aggressive.
    if diff_summary and tests_after < tests_before and len(created) < max_issues:
        has_new_code = any(
            kw in diff_summary.lower()
            for kw in ["added", "new file", "created"]
        )
        if has_new_code and not _has_test_keyword(item.title):
            test_title = f"[Tests] Add test coverage for #{item.issue_number}"

            if not _title_matches(test_title.lower(), existing_titles):
                test_body = (
                    f"## Goal\n"
                    f"Add tests for the implementation in #{item.issue_number}.\n\n"
                    f"**Original issue:** #{item.issue_number} -- {item.title}\n\n"
                    f"Tests regressed ({tests_before} -> {tests_after}) after implementation.\n\n"
                    f"## Spec\n"
                    f"1. Identify new/modified functions from #{item.issue_number}\n"
                    f"2. Write unit tests covering:\n"
                    f"   - Happy path\n"
                    f"   - Edge cases\n"
                    f"   - Error handling\n"
                    f"3. Ensure `go test ./...` (or equivalent) still passes\n\n"
                    f"## Acceptance Criteria\n"
                    f"- Test count returns to at least {tests_before}\n"
                    f"- All tests pass\n"
                    f"- No regressions\n\n"
                    f"---\n"
                    f"_Auto-generated by AIPM follow-up scanner_"
                )
                issue_num = queue.create_issue(
                    title=test_title,
                    body=test_body,
                    labels=["autospec", "spec-defined", "priority:medium"],
                )
                if issue_num:
                    created.append(issue_num)
                    existing_titles.append(test_title.lower())

    # ── 3. Link follow-ups back to the original ──
    if created:
        links = ", ".join(f"#{n}" for n in created)
        queue.add_comment(
            item,
            f"**AIPM Follow-up:** Created {len(created)} follow-up issue(s): {links}",
        )

    return created[:max_issues]


def _title_matches(new_title: str, existing_titles: List[str]) -> bool:
    """Check if a similar title already exists (dedup)."""
    # Extract the core reference: "#123" or key phrase
    for existing in existing_titles:
        # Simple: if they share the same issue reference number
        if f"#{new_title}" in existing or any(
            ref in existing for ref in re.findall(r"#\d+", new_title)
        ):
            return True
    return False


def _extract_unchecked_tasks(body: str) -> List[str]:
    """Get unchecked task items from issue body."""
    tasks = []
    for line in body.split("\n"):
        match = re.match(r"^- \[ \] (.+)", line.strip())
        if match:
            task_text = match.group(1).strip()
            # Skip meta-tasks like "Investigate root cause"
            if len(task_text) > 5:
                tasks.append(task_text)
    return tasks


def _has_test_keyword(title: str) -> bool:
    """Check if the issue is already about tests."""
    lower = title.lower()
    return any(kw in lower for kw in ["test", "spec", "coverage", "verify"])
