"""
Root Cause Analysis -- auto-generate diagnostic issues when tasks are abandoned.

When an issue hits the ABANDON state (too many failed attempts), instead of
just labeling it circuit-breaker, this module:
  1. Analyzes the failure pattern across all attempts
  2. Identifies the root cause (architecture rigidity, missing deps, etc.)
  3. Creates a follow-up "RCA" issue that addresses the underlying problem
  4. Links the original issue so it can be retried after the RCA is resolved

This turns failures into learning opportunities and prevents the same
class of failure from blocking future issues.
"""

import json
from typing import List, Optional, Dict
from dataclasses import dataclass

from .prompt_log import PromptLog


@dataclass
class RCADiagnosis:
    """Root cause analysis result."""
    category: str       # "architecture", "dependency", "test_infra", "scope", "unknown"
    summary: str        # One-line diagnosis
    evidence: List[str] # Supporting evidence from attempts
    recommendation: str # What to do about it
    confidence: float   # 0.0-1.0

    def to_issue_body(self, original_issue: int, project: str) -> str:
        """Generate a GitHub Issue body for the RCA."""
        lines = [
            f"## Root Cause Analysis\n",
            f"**Original Issue:** #{original_issue}",
            f"**Project:** {project}",
            f"**Category:** {self.category}",
            f"**Confidence:** {self.confidence:.0%}\n",
            f"### Diagnosis",
            f"{self.summary}\n",
            f"### Evidence",
        ]
        for e in self.evidence:
            lines.append(f"- {e}")

        lines.append(f"\n### Recommendation")
        lines.append(f"{self.recommendation}")
        lines.append(f"\n---")
        lines.append(f"_Auto-generated by AIPM RCA after repeated failures on #{original_issue}_")
        lines.append(f"\n**Tasks**")
        lines.append(f"- [ ] Investigate root cause: {self.summary}")
        lines.append(f"- [ ] Apply fix or refactor")
        lines.append(f"- [ ] Verify #{original_issue} can be retried after this is resolved")

        return "\n".join(lines)


def analyze_failures(
    prompt_log: PromptLog,
    project: str,
    issue_number: int,
) -> RCADiagnosis:
    """Analyze all failed attempts for an issue and diagnose the root cause.

    This looks at patterns across attempts:
      - Same error every time -> likely architecture or dependency issue
      - Different errors each time -> likely scope too broad
      - Trust violations -> agent is fighting the codebase structure
      - No changes at all -> task description unclear or impossible
    """
    attempts = prompt_log.get_attempts(project, issue_number)
    if not attempts:
        return RCADiagnosis(
            category="unknown",
            summary="No attempts recorded",
            evidence=[],
            recommendation="Manual investigation needed",
            confidence=0.0,
        )

    # Collect all errors across attempts
    all_errors: List[str] = []
    all_strategies: List[str] = []
    trust_violations = 0
    no_changes = 0
    total_attempts = len(attempts)

    for rec in attempts:
        all_strategies.append(rec.prompt_strategy)
        if rec.outcome_status == "trust_violation":
            trust_violations += 1
        if rec.outcome_status == "no_change":
            no_changes += 1
        errors = json.loads(rec.errors_json) if rec.errors_json else []
        all_errors.extend(errors)

    # ── Pattern matching ──

    # 1. Same error repeating = dependency or infra issue (most actionable)
    error_counts: Dict[str, int] = {}
    for e in all_errors:
        # Normalize to first 60 chars
        key = e[:60].strip().lower()
        error_counts[key] = error_counts.get(key, 0) + 1

    repeating_errors = [(e, c) for e, c in error_counts.items() if c >= 2]
    if repeating_errors:
        top_error, count = sorted(repeating_errors, key=lambda x: -x[1])[0]
        return RCADiagnosis(
            category="dependency",
            summary=f"Recurring error across {count} attempts: {top_error}",
            evidence=[
                f"Same error pattern appeared {count} times",
                f"Error: {top_error}",
            ] + _unique_errors(all_errors)[:3],
            recommendation="This error persists across different strategies. "
                         "It likely indicates a missing dependency, misconfigured environment, "
                         "or an API change. Fix the underlying issue first, then retry the original task.",
            confidence=0.85,
        )

    # 2. Trust violations = agent fighting codebase structure
    if trust_violations >= total_attempts * 0.5:
        return RCADiagnosis(
            category="architecture",
            summary="Agent repeatedly violates trust boundaries -- codebase structure conflicts with task requirements",
            evidence=[
                f"{trust_violations}/{total_attempts} attempts hit trust violations",
                "Agent is trying to modify files that should not change",
            ] + _unique_errors(all_errors)[:3],
            recommendation="Refactor the protected file list or restructure the codebase "
                         "to make the required changes possible without violating boundaries. "
                         "Consider extracting an interface or adding an extension point.",
            confidence=0.8,
        )

    # 2. No changes at all = task description problem or impossible task
    if no_changes >= total_attempts * 0.6:
        return RCADiagnosis(
            category="scope",
            summary="Agent cannot make progress -- task may be unclear, impossible, or require context not available in the codebase",
            evidence=[
                f"{no_changes}/{total_attempts} attempts produced no code changes",
                "Agent either doesn't understand the task or can't find relevant code",
            ],
            recommendation="Clarify the task description with more specific file paths, "
                         "function names, or examples. Consider if the task requires "
                         "dependencies or infrastructure not yet in the project.",
            confidence=0.7,
        )

    # 3. Different strategies all failed = scope too broad
    unique_strategies = set(all_strategies)
    if len(unique_strategies) >= 3:
        return RCADiagnosis(
            category="scope",
            summary=f"Task too complex -- {len(unique_strategies)} different strategies all failed",
            evidence=[
                f"Strategies tried: {', '.join(unique_strategies)}",
                f"Total attempts: {total_attempts}",
                "Even simplified approaches failed",
            ] + _unique_errors(all_errors)[:3],
            recommendation="Break this task into smaller, independent sub-tasks. "
                         "Each sub-task should be achievable in a single agent pass. "
                         "Consider splitting the issue into 2-3 separate issues.",
            confidence=0.75,
        )

    # 4. Default: generic analysis
    return RCADiagnosis(
        category="unknown",
        summary=f"Task failed {total_attempts} times across {len(unique_strategies)} strategies",
        evidence=[
            f"Strategies: {', '.join(unique_strategies)}",
            f"Test deltas: {', '.join(str(r.test_delta) for r in attempts)}",
        ] + _unique_errors(all_errors)[:5],
        recommendation="Manual review needed. The failure pattern doesn't match "
                     "known categories. Review the attempt history and consider "
                     "if the task is feasible or if the codebase needs structural changes first.",
        confidence=0.3,
    )


def _unique_errors(errors: List[str]) -> List[str]:
    """Get deduplicated errors."""
    seen = set()
    unique = []
    for e in errors:
        key = e[:80].strip()
        if key not in seen:
            seen.add(key)
            unique.append(e)
    return unique[:10]


def create_rca_issue(
    prompt_log: PromptLog,
    project: str,
    issue_number: int,
    issue_queue,  # GitHubIssueQueue
    project_path: str,
) -> Optional[int]:
    """Analyze failures and create an RCA issue if appropriate.

    Returns the new issue number, or None if not created.
    """
    diagnosis = analyze_failures(prompt_log, project, issue_number)

    if diagnosis.confidence < 0.3:
        return None

    # Create the RCA issue
    title = f"[RCA] #{issue_number}: {diagnosis.summary[:80]}"
    body = diagnosis.to_issue_body(issue_number, project)

    issue_num = issue_queue.create_issue(
        title=title,
        body=body,
        labels=["autospec", "spec-defined", "rca", "priority:high"],
    )

    if issue_num:
        # Comment on the original issue
        issue_queue.add_comment_by_number(
            issue_number,
            f"**AIPM Root Cause Analysis** (confidence: {diagnosis.confidence:.0%})\n\n"
            f"**Diagnosis:** {diagnosis.summary}\n"
            f"**Category:** {diagnosis.category}\n"
            f"**Recommendation:** {diagnosis.recommendation}\n\n"
            f"Created follow-up issue #{issue_num} to address the root cause."
        )

    return issue_num
