"""
Roadmap sync -- reads ROADMAP.md and creates GitHub issues for unchecked items.

This keeps the issue queue fed from the project's roadmap. Run it periodically
or after a milestone completion to ensure all planned work is tracked as issues.

Usage:
  python3 main.py sync-roadmap <project_name>
"""

import re
from pathlib import Path
from typing import List, Optional, Tuple
from .issue_queue import GitHubIssueQueue


def sync_roadmap(
    project_path: Path,
    queue: GitHubIssueQueue,
    dry_run: bool = False,
    max_issues: int = 3,
    min_priority: str = "medium",
) -> List[int]:
    """Scan ROADMAP.md and create issues for unchecked items.

    Returns list of created issue numbers.
    """
    roadmap_path = project_path / "ROADMAP.md"
    if not roadmap_path.exists():
        return []

    text = roadmap_path.read_text()
    created = []

    # Get existing open issue titles to avoid duplicates
    existing_titles = _get_existing_titles(queue)

    # Parse sections and unchecked items
    sections = _parse_roadmap(text)

    priority_order = {"high": 0, "medium": 1, "low": 2}
    min_rank = priority_order.get(min_priority, 1)

    for section_title, phase, priority, items in sections:
        # Skip below minimum priority
        p_rank = priority_order.get(priority, 2)
        if p_rank > min_rank:
            continue

        for item_text in items:
            if len(created) >= max_issues:
                break

            if _is_duplicate(item_text, existing_titles):
                continue

            if dry_run:
                print(f"  WOULD CREATE: [{priority}] {item_text}")
                continue

            issue_title = _make_title(section_title, item_text)
            issue_body = (
                f"## Goal\n"
                f"{item_text}\n\n"
                f"## Context\n"
                f"This task comes from the project roadmap (Phase: {phase}).\n\n"
                f"## Acceptance Criteria\n"
                f"- Implementation complete\n"
                f"- All tests pass\n"
                f"- No regressions\n"
                f"- Update ROADMAP.md checkbox when done\n\n"
                f"---\n"
                f"_Auto-generated by AIPM roadmap sync_"
            )

            issue_num = queue.create_issue(
                title=issue_title,
                body=issue_body,
                labels=["autospec", "spec-defined", f"priority:{priority}"],
            )
            if issue_num:
                created.append(issue_num)
                existing_titles.append(issue_title.lower())

    return created


def _parse_roadmap(text: str) -> List[Tuple[str, str, str, List[str]]]:
    """Parse ROADMAP.md into sections with unchecked items.

    Returns: [(section_title, phase, priority, [unchecked_items])]
    """
    results = []
    current_phase = ""
    current_section = ""
    current_priority = "medium"
    phase_complete = False  # skip items inside ✅-complete phases
    parent_phase_complete = False  # remember the ## Phase N status

    lines = text.split("\n")
    for line in lines:
        # Phase headers: ## Phase 1: Stabilization (v0.9.1)
        phase_match = re.match(r"^##\s+Phase\s+(\d+)", line)
        if phase_match:
            current_phase = line.strip()
            # Detect completed phases: ✅ or COMPLETE in the header
            parent_phase_complete = bool(re.search(r'✅|COMPLETE', current_phase))
            phase_complete = parent_phase_complete
            continue

        # Section headers: ### P1: CI/CD Pipeline
        section_match = re.match(r"^###\s+P(\d+)", line)
        if section_match:
            current_section = line.strip()
            p_num = int(section_match.group(1))
            current_priority = {1: "high", 2: "medium", 3: "medium", 4: "low"}.get(
                p_num, "medium"
            )
            continue

        # Section headers without P-prefix (GPU Integration, etc)
        section_match2 = re.match(r"^###\s+(.+)", line)
        if section_match2:
            header_text = section_match2.group(1).strip()
            current_section = header_text

            # Start by resetting to parent phase status
            phase_complete = parent_phase_complete

            # Detect completed sub-sections (e.g. "Success Criteria: ✅ ALL MET")
            if re.search(r'✅|COMPLETE|ALL MET', header_text):
                phase_complete = True
            # Phase sub-headers (e.g. "Phase 1: Foundation ✅")
            elif re.match(r'Phase\s+\d+', header_text):
                phase_complete = bool(re.search(r'✅|COMPLETE', header_text))
            continue

        # Unchecked items: - [ ] Task description
        unchecked = re.match(r"^- \[ \] (.+)", line)
        if unchecked:
            # Skip items inside completed phases or completed sub-sections
            if phase_complete:
                continue
            item_text = unchecked.group(1).strip()
            if item_text and current_section:
                results.append(
                    (current_section, current_phase, current_priority, [item_text])
                )

    return results


def _get_existing_titles(queue: GitHubIssueQueue) -> List[str]:
    """Get lowercase titles of all open issues to check for duplicates."""
    titles = []
    for item in queue.list_open():
        titles.append(item.title.lower())
    return titles


def _is_duplicate(item_text: str, existing_titles: List[str]) -> bool:
    """Check if an item already exists as an issue.

    Uses substring containment on the full normalized text (first 30+ chars).
    Avoids word-level matching which causes false positives.
    """
    normalized = item_text.lower().strip()

    # Remove leading verbs to get the core concept
    for prefix in ["add ", "create ", "implement ", "build ", "write ", "set up "]:
        if normalized.startswith(prefix):
            normalized = normalized[len(prefix):]
            break

    # Require a substantial substring match (60%+ of the shorter text)
    # This prevents "GitHub Actions: lint" matching "GitHub Actions: test"
    # while still catching true duplicates like rewordings
    threshold = max(30, int(len(normalized) * 0.6))

    for title in existing_titles:
        # Direct containment check
        if normalized[:threshold] in title:
            return True

        # Also check if the title's core is in the new item
        # (handles reverse order: existing title is shorter)
        # Strip tags like [CI/CD Pipeline] for comparison
        clean_title = re.sub(r'\[.*?\]\s*', '', title).strip()
        if len(clean_title) >= threshold and clean_title[:threshold] in normalized:
            return True

    return False


def _make_title(section_title: str, item_text: str) -> str:
    """Create a clean issue title from section and item."""
    # Extract section tag: "### P1: CI/CD Pipeline" -> "[CI/CD Pipeline]"
    tag_match = re.search(r":\s*(.+?)(?:\s*\(|$)", section_title)
    tag = tag_match.group(1).strip() if tag_match else ""

    # Clean up item text for title
    title = item_text.strip()
    if len(title) > 80:
        title = title[:77] + "..."

    # Add tag prefix if meaningful
    if tag and not title.lower().startswith(tag.lower()):
        title = f"[{tag}] {title}"

    return title
