"""
Session Historian - Mines Hermes session transcripts for project knowledge.

Scans ~/.hermes/sessions/*.jsonl, matches sessions to AIPM projects/issues,
extracts structured knowledge (files explored, approaches tried, errors hit,
decisions made), and stores summaries via Ollama for injection into future prompts.
"""

import asyncio
import json
import os
import re
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Any

from .config import CTRM_DB, OLLAMA_URL

# ── Schema ────────────────────────────────────────────────────────────────

SCHEMA = """
CREATE TABLE IF NOT EXISTS session_index (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_file TEXT NOT NULL,           -- basename of the .jsonl file
    session_id TEXT,                      -- extracted from session_meta
    platform TEXT DEFAULT '',             -- telegram, cli, discord, etc.
    project TEXT DEFAULT '',              -- matched AIPM project name
    issue_number INTEGER DEFAULT 0,       -- matched GitHub issue number (0 = none)
    started_at TEXT,                      -- parsed from filename
    message_count INTEGER DEFAULT 0,
    files_explored TEXT DEFAULT '[]',     -- JSON array of file paths read
    files_modified TEXT DEFAULT '[]',     -- JSON array of file paths written
    commands_run TEXT DEFAULT '[]',       -- JSON array of shell commands
    errors_hit TEXT DEFAULT '[]',         -- JSON array of error messages
    tools_used TEXT DEFAULT '{}',         -- JSON dict of tool_name -> count
    ollama_summary TEXT DEFAULT '',       -- generated by Ollama summarization
    raw_extract TEXT DEFAULT '',          -- extracted conversation text (for summarization)
    indexed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    summarized_at TEXT DEFAULT '',
    UNIQUE(session_file)
);
CREATE INDEX IF NOT EXISTS idx_session_project ON session_index(project);
CREATE INDEX IF NOT EXISTS idx_session_issue ON session_index(issue_number);
CREATE INDEX IF NOT EXISTS idx_session_time ON session_index(started_at);
"""

# ── Paths ─────────────────────────────────────────────────────────────────

SESSIONS_DIR = Path.home() / ".hermes" / "sessions"
PROJECTS_DIR = Path.home() / "zion" / "projects"

# Lighter model for background summarization (qwen3.5-tools is too heavy/slow for this)
OLLAMA_SUMMARY_MODEL = "qwen2.5-coder:14b"


class SessionHistorian:
    """Scans, indexes, and summarizes Hermes session transcripts."""

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = db_path or str(CTRM_DB)
        self._init_db()

    def _init_db(self):
        with sqlite3.connect(self.db_path) as conn:
            conn.executescript(SCHEMA)

    # ── Scanning ──────────────────────────────────────────────────────

    def scan_new_sessions(self) -> List[str]:
        """Find session JSONL files not yet in the index."""
        if not SESSIONS_DIR.exists():
            return []

        indexed = set()
        with sqlite3.connect(self.db_path) as conn:
            rows = conn.execute("SELECT session_file FROM session_index").fetchall()
            indexed = {r[0] for r in rows}

        new_files = []
        for f in sorted(SESSIONS_DIR.glob("*.jsonl")):
            if f.name not in indexed:
                new_files.append(str(f))

        return new_files

    # ── Extraction ────────────────────────────────────────────────────

    def extract_session(self, filepath: str) -> Optional[Dict[str, Any]]:
        """Parse a JSONL session file and extract structured knowledge."""
        path = Path(filepath)
        if not path.exists():
            return None

        lines = path.read_text().strip().split("\n")
        if not lines:
            return None

        # Parse session meta
        meta = json.loads(lines[0])
        session_id = meta.get("session_id", "")
        platform = meta.get("platform", "unknown")

        # Parse timestamp from filename: 20260330_151858_7e237279.jsonl
        basename = path.stem
        started_at = ""
        try:
            ts_part = basename[:15]  # 20260330_151858
            started_at = datetime.strptime(ts_part, "%Y%m%d_%H%M%S").isoformat()
        except (ValueError, IndexError):
            pass

        # Extract structured data from conversation
        files_explored = set()
        files_modified = set()
        commands_run = []
        errors_hit = []
        tools_used = {}
        raw_conversation = []
        project_refs = set()
        issue_refs = set()

        for line in lines[1:]:
            try:
                msg = json.loads(line)
            except json.JSONDecodeError:
                continue

            role = msg.get("role", "")
            content = str(msg.get("content", ""))

            # Track tool calls
            for tc in msg.get("tool_calls", []):
                func = tc.get("function", {})
                tool_name = func.get("name", "")
                tools_used[tool_name] = tools_used.get(tool_name, 0) + 1

                # Extract args
                args_str = func.get("arguments", "{}")
                try:
                    args = json.loads(args_str) if isinstance(args_str, str) else args_str
                except json.JSONDecodeError:
                    args = {}

                # File exploration from read_file, patch, write_file
                if tool_name in ("read_file", "write_file", "patch"):
                    fp = args.get("path", args.get("old_string", ""))
                    if fp:
                        if tool_name == "read_file":
                            files_explored.add(fp)
                        else:
                            files_modified.add(fp)

                # Shell commands from terminal
                elif tool_name == "terminal":
                    cmd = args.get("command", "")
                    if cmd:
                        commands_run.append(cmd[:200])

                # Browser navigation
                elif tool_name == "browser_navigate":
                    url = args.get("url", "")
                    if url:
                        commands_run.append(f"browser: {url}")

            # Extract errors from tool responses and assistant messages
            if role == "tool":
                try:
                    tool_data = json.loads(content) if content.startswith("{") else {}
                    if isinstance(tool_data, dict) and tool_data.get("exit_code", 0) not in (0, None):
                        err = str(tool_data.get("error") or tool_data.get("output") or "")[:200]
                        if err and err != "null":
                            errors_hit.append(err)
                except (json.JSONDecodeError, AttributeError):
                    pass

            # Extract project references
            project_matches = re.findall(
                r'/zion/projects/([a-zA-Z0-9_-]+)', content
            )
            project_refs.update(project_matches)

            # Extract issue references (#NNN)
            issue_matches = re.findall(r'(?:^|\s)#(\d{1,5})(?:\s|$|,|\.)', content)
            issue_refs.update(int(i) for i in issue_matches)

            # Build raw conversation text for summarization
            if role in ("user", "assistant"):
                snippet = content[:500]
                if snippet.strip():
                    raw_conversation.append(f"[{role}] {snippet}")

        # Resolve project name
        project = self._resolve_project(project_refs, files_explored | files_modified)

        # Resolve issue number
        issue_number = self._resolve_issue(issue_refs, project)

        return {
            "session_file": path.name,
            "session_id": session_id,
            "platform": platform,
            "project": project,
            "issue_number": issue_number,
            "started_at": started_at,
            "message_count": len(lines),
            "files_explored": sorted(files_explored),
            "files_modified": sorted(files_modified),
            "commands_run": commands_run[:50],
            "errors_hit": errors_hit[:30],
            "tools_used": tools_used,
            "raw_extract": "\n".join(raw_conversation[:200]),  # cap for DB
        }

    def _resolve_project(self, project_refs: set, file_paths: set) -> str:
        """Match session content to an AIPM project name."""
        # Check project refs first
        for ref in project_refs:
            if (PROJECTS_DIR / ref).exists():
                return ref

        # Check file paths
        for fp in file_paths:
            parts = Path(fp).parts
            if "projects" in parts:
                idx = parts.index("projects")
                if idx + 1 < len(parts):
                    return parts[idx + 1]

        return ""

    def _resolve_issue(self, issue_refs: set, project: str) -> int:
        """Try to determine which issue this session relates to."""
        if not issue_refs:
            return 0

        # If we have a project, check prompt_log for recent issues
        if project:
            try:
                with sqlite3.connect(self.db_path) as conn:
                    for issue_num in sorted(issue_refs, reverse=True):
                        row = conn.execute(
                            "SELECT 1 FROM prompt_log WHERE project=? AND issue_number=? LIMIT 1",
                            (project, issue_num),
                        ).fetchone()
                        if row:
                            return issue_num
            except sqlite3.Error:
                pass

        # Return the largest issue number (most likely the active one)
        return max(issue_refs) if issue_refs else 0

    # ── Indexing ───────────────────────────────────────────────────────

    def index_session(self, extracted: Dict[str, Any]) -> int:
        """Store extracted session data in the index."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                INSERT OR REPLACE INTO session_index
                    (session_file, session_id, platform, project, issue_number,
                     started_at, message_count, files_explored, files_modified,
                     commands_run, errors_hit, tools_used, raw_extract)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                extracted["session_file"],
                extracted["session_id"],
                extracted["platform"],
                extracted["project"],
                extracted["issue_number"],
                extracted["started_at"],
                extracted["message_count"],
                json.dumps(extracted["files_explored"]),
                json.dumps(extracted["files_modified"]),
                json.dumps(extracted["commands_run"]),
                json.dumps(extracted["errors_hit"]),
                json.dumps(extracted["tools_used"]),
                extracted["raw_extract"],
            ))
            return conn.execute("SELECT last_insert_rowid()").fetchone()[0]

    # ── Summarization via Ollama ───────────────────────────────────────

    async def summarize_session(self, session_id_or_file: str) -> str:
        """Use Ollama to generate a 'lessons learned' summary from session transcript."""
        # Fetch the raw extract
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            row = conn.execute(
                "SELECT * FROM session_index WHERE session_file=? OR session_id=?",
                (session_id_or_file, session_id_or_file),
            ).fetchone()

        if not row or not row["raw_extract"]:
            return ""

        project = row["project"]
        issue_number = row["issue_number"]
        raw = row["raw_extract"]

        # Truncate to fit context window (qwen3.5-tools has 32k)
        if len(raw) > 12000:
            raw = raw[:6000] + "\n...\n" + raw[-6000:]

        prompt = f"""Analyze this AI agent conversation transcript and extract a concise summary for future reference.

Project: {project}
Issue: #{issue_number}

CONVERSATION:
{raw}

Provide a structured summary with:
1. GOAL: What was the agent trying to accomplish?
2. APPROACH: What strategy/approach did it take?
3. FILES: Key files explored or modified (list paths)
4. ERRORS: Any errors encountered and how they were resolved
5. DECISIONS: Important design or implementation decisions made
6. OUTCOME: What was the result? What worked, what didn't?
7. LESSONS: What should future agents working on this codebase know?

Keep it concise - this will be injected into future prompts as context."""

        summary = await self._call_ollama(prompt)

        # Store the summary
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                UPDATE session_index
                SET ollama_summary=?, summarized_at=?
                WHERE session_file=?
            """, (summary, datetime.now().isoformat(), row["session_file"]))

        return summary

    async def _call_ollama(self, prompt: str) -> str:
        """Call Ollama API for summarization."""
        import aiohttp

        url = f"{OLLAMA_URL}/api/generate"
        payload = {
            "model": OLLAMA_SUMMARY_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {"num_ctx": 16384, "temperature": 0.3},
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    url, json=payload, timeout=aiohttp.ClientTimeout(total=120)
                ) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        return data.get("response", "").strip()
                    else:
                        print(f"  ⚠️ Ollama summarization failed: HTTP {resp.status}")
                        return ""
        except Exception as e:
            print(f"  ⚠️ Ollama summarization error: {e}")
            return ""

    # ── Knowledge Retrieval ────────────────────────────────────────────

    def get_project_history(self, project: str, limit: int = 5) -> List[Dict[str, Any]]:
        """Get session summaries for a project, most recent first."""
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute("""
                SELECT session_file, started_at, issue_number, message_count,
                       files_explored, files_modified, errors_hit,
                       ollama_summary, tools_used
                FROM session_index
                WHERE project=? AND ollama_summary != ''
                ORDER BY started_at DESC
                LIMIT ?
            """, (project, limit)).fetchall()

        return [dict(r) for r in rows]

    def get_issue_history(self, project: str, issue_number: int) -> List[Dict[str, Any]]:
        """Get all session summaries for a specific issue."""
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute("""
                SELECT session_file, started_at, message_count,
                       files_explored, files_modified, errors_hit,
                       ollama_summary, tools_used
                FROM session_index
                WHERE project=? AND issue_number=?
                ORDER BY started_at DESC
            """, (project, issue_number)).fetchall()

        return [dict(r) for r in rows]

    def build_context_for_prompt(self, project: str, issue_number: int = 0) -> str:
        """Build session history context string for injection into AIPM prompts."""
        parts = []

        # Get project-level history
        project_history = self.get_project_history(project, limit=3)
        if project_history:
            parts.append("### SESSION HISTORY (prior work on this project)")
            for entry in project_history:
                ts = entry["started_at"][:10] if entry["started_at"] else "?"
                issue = f"#{entry['issue_number']}" if entry["issue_number"] else "general"
                summary = entry["ollama_summary"]
                if summary:
                    parts.append(f"\n--- Session from {ts} (issue {issue}) ---")
                    parts.append(summary)
                else:
                    # Use raw extracted data if no summary yet
                    files = json.loads(entry.get("files_explored", "[]"))
                    modified = json.loads(entry.get("files_modified", "[]"))
                    errors = json.loads(entry.get("errors_hit", "[]"))
                    if files or modified:
                        parts.append(f"\n--- Session from {ts} (issue {issue}, not summarized) ---")
                        if files:
                            parts.append(f"Files explored: {', '.join(files[:10])}")
                        if modified:
                            parts.append(f"Files modified: {', '.join(modified[:10])}")
                        if errors:
                            parts.append(f"Errors hit: {'; '.join(errors[:5])}")

        # Get issue-specific history
        if issue_number:
            issue_history = self.get_issue_history(project, issue_number)
            issue_entries = [e for e in issue_history if e.get("ollama_summary")]
            if issue_entries:
                parts.append(f"\n### ISSUE #{issue_number} SESSION HISTORY")
                for entry in issue_entries:
                    ts = entry["started_at"][:10] if entry["started_at"] else "?"
                    parts.append(f"\n--- Session from {ts} ---")
                    parts.append(entry["ollama_summary"])

        return "\n".join(parts) if parts else ""

    # ── Batch Operations ───────────────────────────────────────────────

    async def index_and_summarize_all(self, max_summarize: int = 10) -> Dict[str, int]:
        """Index all new sessions and summarize them via Ollama."""
        new_files = self.scan_new_sessions()
        stats = {"indexed": 0, "summarized": 0, "errors": 0}

        for filepath in new_files:
            try:
                extracted = self.extract_session(filepath)
                if not extracted:
                    continue
                self.index_session(extracted)
                stats["indexed"] += 1
                print(f"  📋 Indexed: {extracted['session_file']} "
                      f"(project={extracted['project']}, "
                      f"issue=#{extracted['issue_number']}, "
                      f"{extracted['message_count']} msgs)")
            except Exception as e:
                print(f"  ⚠️ Error indexing {filepath}: {e}")
                stats["errors"] += 1

        # Summarize unsummarized sessions (prioritize those with project matches)
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute("""
                SELECT session_file FROM session_index
                WHERE ollama_summary='' AND raw_extract != '' AND project != ''
                ORDER BY started_at DESC
                LIMIT ?
            """, (max_summarize,)).fetchall()

        for row in rows:
            try:
                summary = await self.summarize_session(row["session_file"])
                if summary:
                    stats["summarized"] += 1
                    print(f"  🧠 Summarized: {row['session_file']}")
            except Exception as e:
                print(f"  ⚠️ Error summarizing {row['session_file']}: {e}")
                stats["errors"] += 1

        return stats

    def index_session_from_output(
        self,
        project: str,
        issue_number: int,
        raw_output: str,
        exit_code: int,
        files_changed: Dict[str, str],
        cwd: str,
    ):
        """Quick-index a completed AIPM run from its captured output.

        This is called from loop.py immediately after a hermes run finishes,
        so we don't have to wait for the JSONL file to appear.
        """
        # Extract what we can from raw_output
        errors = []
        commands = re.findall(r'^\$ (.+)$', raw_output, re.MULTILINE)
        err_matches = re.findall(r'(?:Error|error|ERROR)[:\s]+(.{20,200})', raw_output)
        errors.extend(err_matches[:20])

        files_explored = set()
        files_modified = set(files_changed.keys())

        # Look for file references in output
        file_refs = re.findall(r'(?:reading|Reading|editing|Editing|modifying|Modified)[:\s]+([^\s,]+)', raw_output)
        files_explored.update(file_refs)

        # Build raw extract
        raw_lines = raw_output.split("\n")
        raw_extract = "\n".join(raw_lines[:100])  # first 100 lines

        extracted = {
            "session_file": f"aipm_{project}_{issue_number}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            "session_id": "",
            "platform": "aipm",
            "project": project,
            "issue_number": issue_number,
            "started_at": datetime.now().isoformat(),
            "message_count": len(raw_lines),
            "files_explored": sorted(files_explored),
            "files_modified": sorted(files_modified),
            "commands_run": commands[:30],
            "errors_hit": errors,
            "tools_used": {},
            "raw_extract": raw_extract[:8000],
        }

        return self.index_session(extracted)
